// This file is auto-generated by sync.js.
// You can edit the text fields directly (names, bios, titles, categories).
// Running 'node sync.js' will scan the 'photos/' directory, add new files,
// and remove deleted ones while preserving your manual edits here.

const GALLERY_CONFIG = {
  "photographerName": "Olha Vilkhova",
  "photographerTitle": "Visual Artist & Photographer",
  "photographerBio": "Not professional, but I am making photos with passion =)           (pls believe me)",
  "socialLinks": {
    "personal instagram": "https://instagram.com/olkuuus",
    "photo instagram": "https://instagram.com/ph.olkuu",
    "email": "mailto:[olha.vilkhova47@gmail.com]",
    "unsplash": "https://unsplash.com/@olkus"
  },
  "photos": [
    {
      "id": "photo_1780425408302_9yc387k15",
      "src": "photos/Nature/DSC_0613.jpg",
      "title": " ",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 20mm • f/8 • 1/250s • ISO 200"
    },
    {
      "id": "photo_1780427366127_js6p5lp5a",
      "src": "photos/Nature/fogggggy.jpg",
      "title": "Fogggggy",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 40mm • f/8 • 1/250s • ISO 160"
    },
    {
      "id": "photo_1780440612372_xonkh6hi0",
      "src": "photos/Nature/fogggy.jpg",
      "title": "Fogggy",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 55mm • f/8 • 1/250s • ISO 125"
    },
    {
      "id": "photo_1780427366129_242w20bzb",
      "src": "photos/Nature/gool gool.jpg",
      "title": "Gool Gool",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 55mm • f/5.6 • 1/800s • ISO 800"
    },
    {
      "id": "photo_1780427366130_jg1ovwneu",
      "src": "photos/Nature/Greece.jpg",
      "title": "Greece",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 55mm • f/5.6 • 1/800s • ISO 800"
    },
    {
      "id": "photo_1780427366132_hgo8jlkkm",
      "src": "photos/Nature/Greece2.jpg",
      "title": "Greece2",
      "category": "Nature",
      "cameraSettings": "iPhone 12 Pro Max • 5.1mm • f/1.6 • 1/9200s • ISO 32"
    },
    {
      "id": "photo_1780427366135_s1hemn8ap",
      "src": "photos/Nature/looks like a movie.jpg",
      "title": "Looks Like A Movie",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 50mm • f/10 • 1/400s • ISO 100"
    },
    {
      "id": "photo_1780427366136_ql1vcs06b",
      "src": "photos/Nature/plane.jpg",
      "title": "Plane",
      "category": "Nature",
      "cameraSettings": "iPhone 12 Pro Max • 5.1mm • f/1.6 • 1/8500s • ISO 32"
    },
    {
      "id": "photo_1780440612374_a7qet58mx",
      "src": "photos/Nature/rainbow.jpg",
      "title": "Rainbow",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 20mm • f/5.6 • 1/4000s • ISO 160"
    },
    {
      "id": "photo_1780427366137_vfsp3y6mp",
      "src": "photos/Nature/sky.jpg",
      "title": "Sky",
      "category": "Nature",
      "cameraSettings": "iPhone 12 Pro Max • 1.54mm • f/2.4 • 1/150s • ISO 25"
    },
    {
      "id": "photo_1780427366138_1ggcjzyy6",
      "src": "photos/Nature/tree lol.jpg",
      "title": "Tree Lol",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 40mm • f/5.6 • 1/800s • ISO 800"
    },
    {
      "id": "photo_1780427366140_8bsc6zm4r",
      "src": "photos/Nature/trtl.jpg",
      "title": "Trtl",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 55mm • f/5.6 • 1/800s • ISO 800"
    },
    {
      "id": "photo_1780440612376_ya4ltqs82",
      "src": "photos/Nature/volcano (another pov).jpg",
      "title": "Volcano (Another Pov)",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 18mm • f/8 • 1/250s • ISO 110"
    },
    {
      "id": "photo_1780440612378_6o5qyp99b",
      "src": "photos/Nature/volcano.jpg",
      "title": "Volcano",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 35mm • f/10 • 1/80s • ISO 200"
    },
    {
      "id": "photo_1780440612380_vsbyjv9ta",
      "src": "photos/Nature/what about God.jpg",
      "title": "What About God",
      "category": "Nature",
      "cameraSettings": "NIKON D5100 • 38mm • f/5 • 1/40s • ISO 2500"
    },
    {
      "id": "photo_1780440612381_5hqr8a63f",
      "src": "photos/Portraits/A.jpg",
      "title": "A",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 26mm • f/5 • 1/100s • ISO 1600"
    },
    {
      "id": "photo_1780440612382_i9l2gqev0",
      "src": "photos/Portraits/A1.jpg",
      "title": "A1",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 18mm • f/5 • 1/100s • ISO 1600"
    },
    {
      "id": "photo_1780440612383_6jybemdea",
      "src": "photos/Portraits/A2.jpg",
      "title": "A2",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 18mm • f/5 • 1/100s • ISO 1600"
    },
    {
      "id": "photo_1780440612388_g9gfvvcic",
      "src": "photos/Portraits/A4.jpg",
      "title": "A4",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 24mm • f/5 • 1/80s • ISO 1600"
    },
    {
      "id": "photo_1780440612389_s60vbbdyp",
      "src": "photos/Portraits/Brightstar.jpg",
      "title": "Brightstar",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 34mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780427366143_lle89tep6",
      "src": "photos/Portraits/cmfrt.jpg",
      "title": "Cmfrt",
      "category": "Portraits",
      "cameraSettings": "iPhone 12 Pro Max • 5.1mm • f/1.6 • 1/60s • ISO 400"
    },
    {
      "id": "photo_1780440612391_6rsnw00wl",
      "src": "photos/Portraits/dtsh.jpg",
      "title": "Dtsh",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 29mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780440612392_5ifopyocj",
      "src": "photos/Portraits/dtsh2.jpg",
      "title": "Dtsh2",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 36mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780426829010_ihhdm8owf",
      "src": "photos/Portraits/holy - i like the atmosphere here.jpg",
      "title": "holy",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 26mm • f/4.2 • 1/25s • ISO 3200"
    },
    {
      "id": "photo_1780440857797_06ppzzd2r",
      "src": "photos/Portraits/kt, refresh.jpg",
      "title": "Kt, Refresh",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 45mm • f/8 • 1/250s • ISO 200"
    },
    {
      "id": "photo_1780440612393_vxpm5mzrv",
      "src": "photos/Portraits/kt.jpg",
      "title": "Kt",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 55mm • f/6.3 • 1/160s • ISO 200"
    },
    {
      "id": "photo_1780426829011_i3j3u1gr0",
      "src": "photos/Portraits/late night - i love how this pic look like an album cover.jpg",
      "title": "late night",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 18mm • f/5 • 1/30s • ISO 5000"
    },
    {
      "id": "photo_1780440612394_35d3vdvll",
      "src": "photos/Portraits/masha.jpg",
      "title": "Masha",
      "category": "Portraits",
      "cameraSettings": "NIKON D7500 • 27mm • f/4.5 • 1/20s • ISO 2000"
    },
    {
      "id": "photo_1780426829012_gofvdfmhz",
      "src": "photos/Portraits/metro.jpg",
      "title": "Metro",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 18mm • f/5.6 • 1/80s • ISO 2500"
    },
    {
      "id": "photo_1780426829013_9em7woasl",
      "src": "photos/Portraits/Nzr.jpg",
      "title": "Nzr",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 24mm • f/4 • 1/60s • ISO 3200"
    },
    {
      "id": "photo_1780426829013_0twdxzc5w",
      "src": "photos/Portraits/Nzr2.jpg",
      "title": "Nzr2",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 35mm • f/5 • 1/60s • ISO 3200"
    },
    {
      "id": "photo_1780426829015_uxr43gaqg",
      "src": "photos/Portraits/Nzr4.jpg",
      "title": "Nzr4",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 42mm • f/5.6 • 1/60s • ISO 1600"
    },
    {
      "id": "photo_1780440612396_qck0zqli7",
      "src": "photos/Portraits/pp.jpg",
      "title": "Pp",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 36mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780440857799_jwku6owm4",
      "src": "photos/Portraits/psch.jpg",
      "title": "Psch",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 30mm • f/4.5 • 1/30s • ISO 1250"
    },
    {
      "id": "photo_1780440612400_oma6z4w1v",
      "src": "photos/Portraits/rs.jpg",
      "title": "Rs",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 36mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780440612402_976o88b2e",
      "src": "photos/Portraits/rs2.jpg",
      "title": "Rs2",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 36mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780440857801_7cr7cf7zu",
      "src": "photos/Portraits/vsr.jpg",
      "title": "Vsr",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 29mm • f/5.6 • 1/4000s • ISO 320"
    },
    {
      "id": "photo_1780440612403_txksyzr4s",
      "src": "photos/Portraits/vsr2.jpg",
      "title": "Vsr2",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 18mm • f/10 • 1/320s • ISO 200"
    },
    {
      "id": "photo_1780440612404_ss2pxi5v6",
      "src": "photos/Portraits/vsr3.jpg",
      "title": "Vsr3",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 46mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780440612405_kndhpxkcl",
      "src": "photos/Portraits/vsr4.jpg",
      "title": "Vsr4",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 40mm • f/5.6 • 1/4000s • ISO 320"
    },
    {
      "id": "photo_1780440612406_qwin33cny",
      "src": "photos/Portraits/what a nice weather!.jpg",
      "title": "What A Nice Weather!",
      "category": "Portraits",
      "cameraSettings": "NIKON D5100 • 55mm • f/5.6 • 1/1000s • ISO 125"
    },
    {
      "id": "photo_1780440612408_z2jq51ci9",
      "src": "photos/Random/do not look up.jpg",
      "title": "Do Not Look Up",
      "category": "Random",
      "cameraSettings": "NIKON D5100 • 42mm • f/5.3 • 1/1000s • ISO 320"
    },
    {
      "id": "photo_1780427366146_m5x6ltrnw",
      "src": "photos/Random/even-ing.jpg",
      "title": "Even Ing",
      "category": "Random",
      "cameraSettings": "NIKON D5100 • 30mm • f/4.5 • 1/40s • ISO 1250"
    },
    {
      "id": "photo_1780427366147_wko9ywf1p",
      "src": "photos/Random/isn't it random.jpg",
      "title": "Isn'T It Random",
      "category": "Random",
      "cameraSettings": "iPhone 12 Pro Max • 5.1mm • f/1.6 • 1/35s • ISO 640"
    },
    {
      "id": "photo_1780427366148_o5r13q6u3",
      "src": "photos/Random/kake.jpg",
      "title": "Kake",
      "category": "Random",
      "cameraSettings": "iPhone 12 Pro Max • 5.1mm • f/1.6 • 1/1250s • ISO 32"
    },
    {
      "id": "photo_1780427366150_nab3rfn5f",
      "src": "photos/Random/let's dance.jpg",
      "title": "Let'S Dance",
      "category": "Random",
      "cameraSettings": "iPhone 12 Pro Max • 1.54mm • f/2.4 • 1/60s • ISO 400"
    },
    {
      "id": "photo_1780427366152_znwfpdosr",
      "src": "photos/Random/rain.jpg",
      "title": "Rain",
      "category": "Random",
      "cameraSettings": "iPhone 12 Pro Max • 5.1mm • f/1.6 • 1/19s • ISO 800"
    },
    {
      "id": "photo_1780427366153_3p4uux3ow",
      "src": "photos/Random/ride.jpg",
      "title": "Ride",
      "category": "Random",
      "cameraSettings": "NIKON D5100 • 38mm • f/5 • 1/30s • ISO 1000"
    },
    {
      "id": "photo_1780440612409_yg9gmh1fn",
      "src": "photos/Random/super women.jpg",
      "title": "Super Women",
      "category": "Random",
      "cameraSettings": "NIKON D5100 • 45mm • f/8 • 1/250s • ISO 140"
    },
    {
      "id": "photo_1780427366154_pum2d65qp",
      "src": "photos/Random/talk.jpg",
      "title": "Talk",
      "category": "Random",
      "cameraSettings": "NIKON D5100 • 48mm • f/5.6 • 1/40s • ISO 800"
    },
    {
      "id": "photo_1780427366156_1fabwcnkx",
      "src": "photos/Random/_.jpg",
      "title": " ",
      "category": "Random",
      "cameraSettings": "NIKON D5100 • 32mm • f/5.6 • 1/640s • ISO 1000"
    }
  ]
};
